AWSTemplateFormatVersion: 2010-09-09
Description: STS AssumeRole demo role with limited S3 permissions

Parameters:
  AccountId:
    Type: String
  UserName:
    Type: String
  RoleName:
    Type: String
  BucketName:
    Type: String

Resources:
  STSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AccountId}:user/${UserName}
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: s3ScopedAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ListBucket
                Effect: Allow
                Action: s3:ListBucket
                Resource: !Sub arn:aws:s3:::${BucketName}
              - Sid: ObjectRW
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub arn:aws:s3:::${BucketName}/*
Outputs:
  RoleArn:
    Value: !GetAtt STSRole.Arn
    Description: ARN of the role to assume
